version: '3.8'

services:
    pg-database:
        image: postgres:13
        container_name: pg-database
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: ny_taxi
        volumes:
            - "D:/ny_taxi_postgres_data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    pg-admin:
        image: dpage/pgadmin4
        container_name: pg-admin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
          - pg-database